### ISSUE TITLE
Feature | Add some good useful Android Libraries

### ISSUE THREAD

**Issue by imniladri** [imniladri/DevHub#1]
**The Android Pack page is empty. Add some awesome cool libraries.**

What to do:
- Research and find some libraries.
- Added them to [`android.data.js`](https://github.com/imniladri/DevHub/blob/dev/client/data/android.data.js).
- And make other necessary changes.

**Comment by rishvantsingh** [comment]
Allot it to me . I will do it.

**Comment by imniladri** [comment]
> Allot it to me . I will do it.

Sure!
But this project is currently under [**JWOC'22**](https://jwoc.tech/).
If you want to contribute, kindly register yourself for the program, [**here**](https://jwoc.tech/auth/student-register).
And check out the **timeline** to know about contribution.

**Comment by rishvantsingh** [comment]
OKh I will register but can i contribute like right now or not ?

**Comment by imniladri** [comment]
Right now, You can't till the coding period starts (1st Feb).

**Comment by polarizz17** [comment]
I want to work on this issue under JWOC, Sir.

**Comment by Srijita-Mandal** [comment]
Hii, I want to work on this issue under JWOC

**Comment by ayush-sleeping** [comment]
I want to work on this issue under JWOC

**Comment by imniladri** [comment]
@polarizz17 Go on!
