### ISSUE TITLE
Feature | Add some good useful daily use API Libraries

### ISSUE THREAD

**Issue by imniladri** [imniladri/DevHub#2]
**The API Pack page is empty. Add some awesome cool libraries.**

What to do:
- Research and find some libraries.
- Added them to [`api.data.js`](https://github.com/imniladri/DevHub/blob/dev/client/data/api.data.js).
- And make other necessary changes.

**Comment by iathul** [comment]
@imniladri I can work on this

**Comment by imniladri** [comment]
> @imniladri I can work on this

Sure!
But this project is currently under [**JWOC'22**](https://jwoc.tech/).
If you want to contribute, kindly register yourself for the program, [**here**](https://jwoc.tech/auth/student-register).
And check out the **timeline** to know about contribution.

**Comment by Srijita-Mandal** [comment]
Hii, I want to work on this issue under JWOC

**Comment by imniladri** [comment]
@Srijita-Mandal Go for it

**Comment by Srijita-Mandal** [comment]
@imniladri , As this is the third issue I am assigned, so can you please unassign me until I complete atleast on of those two issues?
