### ISSUE TITLE
Bug | 404 Page isn't matching with the theme

### ISSUE THREAD

**Issue by imniladri** [imniladri/DevHub#25]
404 Page isn't matching with the theme fix it.

What to do:
- Also use the SVG file that is provided in the `img` directory [`error.svg`](https://github.com/imniladri/DevHub/blob/dev/client/img/error.svg)
- And make other necessary changes for a better UI.

**Comment by RajulPE** [comment]
I want to work on this issue under JWOC.

**Comment by imniladri** [comment]
> I want to work on this issue under JWOC.

Great also comment in discord too!

**Comment by imniladri** [comment]
Go for it @RajulPE
