### ISSUE TITLE
Feature | Add some cool page transitions

### ISSUE THREAD

**Issue by imniladri** [imniladri/DevHub#27]
**Needed page transitions, when a user visits from one page to another.**

What to do:
- **Some kinds of animations from one page to another**, such as **sliding, fading**, etc.
- Can use any library or manually but make sure it looks great.
- Do other necessary changes for a good and better UI.

**Comment by mridul4101** [comment]
I would like to try and contribute to this issue under JWOC.

**Comment by imniladri** [comment]
Great @mridul4101, Go for it.

**Comment by Srijita-Mandal** [comment]
@imniladri ,Can I work on this issue under JWoC? I am not sure whether I can do it, but I can try my best.

**Comment by imniladri** [comment]
Go for it @Srijita-Mandal, Try it out.
