### ISSUE TITLE
Doc | Add more libraries in library page

### ISSUE THREAD

**Issue by imniladri** [imniladri/DevHub#28]
**Needed more useful libraries and resources in library pack pages.**

What to do:
1. More awesome CSS, JS, Android, API libraries.
2. More awesome Icons, Images resources, etc.
2. Make sure that your library doesn't exist before, check it before adding anything.

**Comment by Srijita-Mandal** [comment]
I want to work on this issue under JWoC

**Comment by imniladri** [comment]
Go for it @Srijita-Mandal

**Comment by imniladri** [comment]
Changed Label,
So take time for adding libs, research, and add quite a no. of them.

**Comment by Srijita-Mandal** [comment]
Okay
