### ISSUE TITLE
Feature | 404 (Page Not Found) Page required

### ISSUE THREAD

**Issue by imniladri** [imniladri/DevHub#3]
**Added the page not found error page and design it & make it awesome.**

What to do:
- Design the 404 page, add your HTML in [`404.html`](https://github.com/imniladri/DevHub/blob/dev/client/404.html).
- Create an `error.css` stylesheet in `/css/pages` directory & make your changes.
- Must use the fonts and colors variables that are in [`settings.css`](https://github.com/imniladri/DevHub/blob/dev/client/css/components/settings.css).
- Also use the SVG file that is provided in the `img` directory [`error.svg`](https://github.com/imniladri/DevHub/blob/dev/client/img/error.svg)
- And make other necessary changes.

**Comment by 7ORP3DO** [comment]
Hii @imniladri, I want to work on this issue.
Kindly assign me on this Issue.

**Comment by imniladri** [comment]
> Hii @imniladri, I want to work on this issue. Kindly assign me on this Issue.

Sure!
But this project is currently under [**JWOC'22**](https://jwoc.tech/).
If you want to contribute, kindly register yourself for the program, [**here**](https://jwoc.tech/auth/student-register).
And check out the **timeline** to know about contribution.

**Comment by Srijita-Mandal** [comment]
Hii, Can I contribute on this issue? I am registered in JWOC. Can I be assigned to contribute after 1st feb?

**Comment by imniladri** [comment]
> Hii, Can I contribute on this issue? I am registered in JWOC. Can I be assigned to contribute after 1st feb?

Yeah sure, will assign you first!

**Comment by imniladri** [comment]
@Srijita-Mandal
There is a mistake please start commenting from 1st Feb.

**Comment by Lavanyabisht11** [comment]
I want to work on this issue under JWOC

**Comment by Arun5023** [comment]
"I want to work on this issue under JWOC"

**Comment by ShrutiKapure** [comment]
I want to work on this issue under **JWOC**.

**Comment by imniladri** [comment]
@Lavanyabisht11 Go on work out!

**Comment by raxvab** [comment]
I want to work with this issue

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC
