### ISSUE TITLE
Feature | Add ML libraries 

### ISSUE THREAD

**Issue by wasimreja** [imniladri/DevHub#34]
There is no ML Pack page. Add some useful ML libraries.

**Comment by wasimreja** [comment]
I want to work on this issue under JWoC.

**Comment by imniladri** [comment]
Go for it @wasimreja

**Comment by wasimreja** [comment]
@imniladri bhaiya could you assign the label as medium? ML Pack page isn't created previously. I have to create the page, integrate it with other pages and then add the libraries.

**Comment by imniladri** [comment]
Ok sure, I was too thinking about it that it may take time.

> @imniladri bhaiya could you assign the label as medium? ML Pack page isn't created previously. I have to create the page, integrate it with other pages and then add the libraries.
