### ISSUE TITLE
Feature | Add Confetti Particles to the Loader Screen

### ISSUE THREAD

**Issue by imniladri** [imniladri/DevHub#4]
**Add some awesome confetti particles to the loading screen.**

What to do:
- Gather some cool **colorful confetti** particles.
- Can use the `particles.js` library for this, which is **already** added in `/js/libraries` directory.
- Create a `sketch.app.js` file for the configuration of the particles js and use this file for **awesome customization**.
- Make the particles **only** for the loading screen.
- And make other necessary changes that fit in and make UI be good.

**Comment by Devmindtk** [comment]
I would like to work on this issue @imniladri  please assign it to me.

**Comment by imniladri** [comment]
> I would like to work on this issue @imniladri please assign it to me.

Yeah sure,
Just give a comment in the channel on discord and will assign you after the contribution starts.

**Comment by Devmindtk** [comment]
> > I would like to work on this issue @imniladri please assign it to me.
> 
> Yeah sure, Just give a comment in the channel on discord and will assign you after the contribution starts.

Can you please share me the channel link?

**Comment by imniladri** [comment]
> > > I would like to work on this issue @imniladri please assign it to me.
> > 
> > 
> > Yeah sure, Just give a comment in the channel on discord and will assign you after the contribution starts.
> 
> Can you please share me the channel link?

Join our server there you will find this project channel.
And comment on issues after 1st Feb. This comment will count as invalid.

**Comment by vish-han** [comment]
I want to work on this issue under JWOC

**Comment by imniladri** [comment]
Go on @vish-han

**Comment by vish-han** [comment]
How much time is assigned for medium labeled issues?

**Comment by imniladri** [comment]
> How much time is assigned for medium labeled issues?

2-3 days
Also, you can check that out by hovering the label.

**Comment by imniladri** [comment]
@vish-han Are you still working on it? Please comment on discord.

**Comment by Aniket-508** [comment]
I want to work on this under JWOC.
