### ISSUE TITLE
Feature | Create a Color Theme Shifter for the Site

### ISSUE THREAD

**Issue by imniladri** [imniladri/DevHub#7]
**Create a theme changer or shifter for the whole website, which changes the main color theme for the site.**

What to do:
- Make a theme shifter that **changes** the main color theme. **(Current Color Theme: Blue+Yellow)**
- Choose some color combinations for other themes, **Minimum 3-4**. [_Get Here_](https://colorhunt.co/)
- Place the theme shifter in the **footer section**.
- Try to use variables for the colors in a separate `theme.css` file in [`/css/components`](https://github.com/imniladri/DevHub/tree/dev/client/css/components) directory.
- And make other necessary changes and make sure that the UI be good.
- Also use proper **documentation** for writing the code.

Challenge:
- The main challenge is that the **selected theme may remain the same after the user closes the site or reload the page**.
- And it is for **each theme**.

Example: [**See an Example Here: My Site**](https://imniladri.in/)

**Comment by vish-han** [comment]
I want to contribute to this issue 😁

**Comment by imniladri** [comment]
> I want to contribute to this issue 😁

Great, but our contribution starts tomorrow.
And please also comment on the channel in our discord server if you are interested we will take it from there.

**Comment by mridul4101** [comment]
I want to work on this issue under JWOC

**Comment by PrajwalDhule** [comment]
hello, I would like to work on this issue

**Comment by imniladri** [comment]
@mridul4101 Go for it!
