### ISSUE TITLE
Feature | Create a Form for Users to Add Library

### ISSUE THREAD

**Issue by imniladri** [imniladri/DevHub#8]
**Create a beautiful form that helps users to submit new libraries for the hub.**

What to do:
- Add a form with the **required fields mentioned below** in [`new.html`](https://github.com/imniladri/DevHub/blob/dev/client/new.html) file.
- Create **custom stylings** for **each** form field and add your styles in [`form.css`](https://github.com/imniladri/DevHub/blob/dev/client/css/pages/form.css) file.
- Try to use the color theme we provided in [`settings.css`](https://github.com/imniladri/DevHub/blob/dev/client/css/components/settings.css) file.
- And make other necessary changes and make the UI best looking.

Fields:

Add these fields must and you can also add any extra info field.
- Name:
- Email:
- Library Name:
- Library Link:
- Library Category: (Use **radio or dropdown** for this)
- Library Description:
- Uses of the Library:

**Comment by NaK915** [comment]
Hey there!! I would love to contribute to this issue. Can I do it under your mentorship?

**Comment by imniladri** [comment]
> Hey there!! I would love to contribute to this issue. Can I do it under your mentorship?

Just comment on the issue after 1st Feb.
For it will be not valid.

**Comment by Sanghu01** [comment]
Hey, This is Sangh Priya Gautam .I am intrested in contributing to this project but how can i work in this project .

**Comment by imniladri** [comment]
> Hey, This is Sangh Priya Gautam .I am intrested in contributing to this project but how can i work in this project .

Try commenting on issues from tomorrow.
And ask your queries in the respective discord channel.

**Comment by Sanghu01** [comment]
ok sir.

**Comment by sahilkr9** [comment]
I want to work on this issue under JWOC

**Comment by PrajwalDhule** [comment]
hello, I would like to work on this issue

**Comment by NaK915** [comment]
Hey there!! I would love to contribute to this repository by working on this issue. Would you provide the opportunity to do this under your guidance?

**Comment by imniladri** [comment]
Going to issue the next one if not completed by @sahilkr9 in 1 day.

**Comment by raxvab** [comment]
I want to work with this issue under JWOC

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC
