### ISSUE TITLE
Feature:  Create a register and sign up form

### ISSUE THREAD

**Issue by priyanka001tech** [imniladri/DevHub#9]
### Is your feature request related to a problem? Please describe.

I found there is no authentication system in this website so I'll like to contribute in it.

### Describe the solution you'd like

A register and sign up page will be there for user .

**Comment by imniladri** [comment]
@priyanka001tech 
I like to know that if registered for our event, join our discord server. And comment on the respective channel for further communication about working on issues and contribution.

**Comment by priyanka001tech** [comment]
> @priyanka001tech I like to know that if you registered for our event, join our discord server. And comment on the respective channel for further communication about working on issues and contribution.

Yes I've registered. Okay I'll do it

**Comment by imniladri** [comment]
> 

Will reopen this issue after coding starts. Closing for now.
